repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4  # Replace with latest ruff version
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.0  # Replace with latest black version
    hooks:
      - id: black

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0  # check for the latest version on GitHub
  #   hooks:
  #     - id: mypy
